### ISSUE TITLE
Architec practica 1

### ISSUE THREAD

**Issue by luzm23** [SistemasTecTlaxiaco/actividad-3-practica-architect-luzm23#1]
[Diagrama De clase En Architec practica 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-luzm23/files/12555694/Diagrama.De.clase.En.Architec.practica.1.pdf)

**Comment by YaelStO** [comment]
Buen Trabajo 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
